/********************************************************************
 *   This C program was generated by spl2c, the Shakespeare to C    *
 *          converter by Jon Åslund and Karl Hasselström.           *
 ********************************************************************/

/* libspl definitions and function prototypes */
#include <spl.h>

int main(void)
{
  /******************************************************************
   * BY PETER NILLIUS 2001 - 08 - 31 < NILLIUS AT NADA DOT KTH DOT SE > FIBONACCI ' S NUMBERS*
   ******************************************************************/
  
  CHARACTER *romeo;                       /* a lover with an accumulative memory */
  CHARACTER *juliet;                      /* a beautiful but domineering woman */
  CHARACTER *ulysses;                     /* a spaceman */
  
  int comp1, comp2;
  
  global_initialize();
  
  romeo = initialize_character("Romeo");
  juliet = initialize_character("Juliet");
  ulysses = initialize_character("Ulysses");
  
  act_i:                                  /* A Minimalistic Play */
  
  act_i_scene_i:                          /* Juliet Sets Things Straight */
  
  enter_scene(15, romeo);
  enter_scene(15, juliet);
  
  activate_character(22, juliet);
  assign(18, second_person, 0);
  push(18, second_person, value_of(18, second_person));
  assign(19, second_person, int_sub(19, 0, (-1)));
  int_output(20, second_person);
  
  exit_scene(22, romeo);
  
  enter_scene(24, ulysses);
  
  activate_character(30, juliet);
  assign(28, second_person, int_twice(27, int_square(27, int_mul(27, 2*(-1), 2*(-1)))));
  char_output(28, second_person);
  
  act_i_scene_ii:                         /* Accumulative Juggling */
  
  exit_scene(32, ulysses);
  
  enter_scene(34, romeo);
  
  activate_character(39, romeo);
  assign(37, second_person, value_of(37, first_person));
  
  activate_character(43, juliet);
  pop(40, second_person);
  assign(40, second_person, int_add(40, value_of(40, first_person), value_of(40, second_person)));
  comp1 = value_of(41, second_person);
  comp2 = 0;
  truth_flag = (comp1 > comp2);
  
  activate_character(46, romeo);
  if (!truth_flag) {
    goto act_i_scene_iv;
  }
  
  activate_character(49, juliet);
  int_output(47, second_person);
  push(47, second_person, value_of(47, first_person));
  
  exit_scene(49, romeo);
  
  act_i_scene_iii:                        /* A Spaceman Interferes */
  
  enter_scene(53, ulysses);
  
  activate_character(58, juliet);
  char_output(56, second_person);
  
  activate_character(61, ulysses);
  goto act_i_scene_ii;
  
  act_i_scene_iv:                         /* Romeo ' s head overflows */
  
  exit_scene_all(63);
  
  return 0;
}
